server:
  port: 8082
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/ordermanagement_micro
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update